In [1]:
import numpy as np

inputs = [[1,2,3,2],[2,4,5,3],[-1,2,4,3]]
weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]

output = np.dot(inputs,np.array(weights).T) + biases
print(output)



[[4.3  1.46 1.95]
 [6.1  0.16 2.36]
 [4.4  0.22 3.51]]


In [5]:
from nnfs.datasets import spiral_data
import nnfs

nnfs.init()


