In [1]:
import numpy as np

inputs = [[1,2,3,2],[2,4,5,3],[-1,2,4,3]]
weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]

output = np.dot(inputs,np.array(weights).T) + biases
print(output)



[[4.3  1.46 1.95]
 [6.1  0.16 2.36]
 [4.4  0.22 3.51]]


In [1]:
class DenseLayer:

    def __init__(self, n_inputs, n_neurons):

        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):

        self.output = np.dot(inputs, self.weights) + self.biases


In [ ]:
class Activation_ReLU:

    def forward(self, inputs):

        self.output = np.maximum(0, inputs)


In [2]:
class Activation_Softmax:

    def forward(self, inputs):

        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

        self.output = probabilities

In [3]:
class Loss:

    def calculate(self, output, y):

        sample_losses = self.forward(output, y)

        data_loss = np.mean(sample_losses) 

        return data_loss

In [4]:
class Loss_CategoricalCrossentropy(Loss):

    def forward(self, y_pred, y_true):

        samples = len(y_pred)

        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)

        return negative_log_likelihoods