In [3]:
import numpy as np

inputs = [[1,2,3,2],[2,4,5,3],[-1,2,4,3]]
weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]

output = np.dot(inputs,np.array(weights).T) + biases
print(output)



[[4.3  1.46 1.95]
 [6.1  0.16 2.36]
 [4.4  0.22 3.51]]


In [4]:
class DenseLayer:

    def __init__(self, n_inputs, n_neurons):

        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):

        self.output = np.dot(inputs, self.weights) + self.biases


In [5]:
class Activation_ReLU:

    def forward(self, inputs):

        self.output = np.maximum(0, inputs)


In [6]:
class Activation_Softmax:

    def forward(self, inputs):

        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

        self.output = probabilities

In [7]:
class Loss:

    def calculate(self, output, y):

        sample_losses = self.forward(output, y)

        data_loss = np.mean(sample_losses) 

        return data_loss

In [8]:
class Loss_CategoricalCrossentropy(Loss):

    def forward(self, y_pred, y_true):

        samples = len(y_pred)

        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)

        return negative_log_likelihoods

In [10]:
import nnfs
from nnfs.datasets import spiral_data
    
nnfs.init()

X, y = spiral_data(100, 3)

dense1 = DenseLayer(2, 3)

activation1 = Activation_ReLU()   

dense2 = DenseLayer(3, 3)

activation2 = Activation_Softmax()

loss_function = Loss_CategoricalCrossentropy()

dense1.forward(X)

activation1.forward(dense1.output)

dense2.forward(activation1.output)

activation2.forward(dense2.output)

print(activation2.output[:5])

loss = loss_function.calculate(activation2.output, y)

print("Loss:", loss)

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
Loss: 1.0986104


In [14]:
predictions = np.argmax(activation2.output, axis=1)
if len(y.shape) == 2:
    y = np.argmax(y,axis=1)
accuracy = np.mean(predictions == y)

print('acc:', accuracy)

acc: 0.34


In [4]:
weights = np.array([[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]).T

In [5]:
print(weights)

[[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]


In [6]:
print(weights.T)

[[ 0.2   0.8  -0.5   1.  ]
 [ 0.5  -0.91  0.26 -0.5 ]
 [-0.26 -0.27  0.17  0.87]]


In [4]:
dvalues = np.array([[1.,1.,1.],[2.,2.,2.],[3.,3.,3.]])

In [14]:
biases = np.array([[2,3,0.5]])

In [15]:
print(biases.shape)

(1, 3)


In [19]:
dbiases = np.sum(dvalues, axis=0, keepdims=True)
print(dbiases)

[[6. 6. 6.]]


In [21]:
z = np.array([[1,2,-3,-4],[2,-7,-1,3],[-1,2,5,-1]])
dvalues = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [22]:
drelu = np.zeros_like(z)
print(drelu)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
drelu[z>0]=1
print(drelu)

[[1 1 0 0]
 [1 0 0 1]
 [0 1 1 0]]


In [46]:
y_true = np.array([2, 1, 2, 0, 1, 2, 1])
y_true = y_true.astype(int)
print(len(y_true.shape))

1


In [40]:
samples = len(dvalues)
print(samples)

3


In [41]:
labels = len(dvalues[0])
print(labels)

4


In [47]:
y_true = np.eye(labels)[y_true]
print(y_true)

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
